#!/usr/bin/env bash
# ClawForge — Stage 1: Architect
# Reads user request, produces a technical plan
set -euo pipefail

REQUEST="${1:-}"
STATE_FILE="${CLAWFORGE_STATE:-$HOME/.openclaw/workspace/clawforge-state.json}"

if [ -z "$REQUEST" ]; then
  echo "Usage: plan.sh \"user request\""
  exit 1
fi

# Check jq is available
if ! command -v jq &>/dev/null; then
  echo "❌ jq is required but not installed." >&2
  exit 1
fi

echo "🧠 Architect: Analyzing request..."

# Encode task as JSON string (handles quotes, newlines, etc.)
TASK_JSON=$(echo "$REQUEST" | jq -Rs .) || { echo "❌ Failed to encode request" >&2; exit 1; }

# Initialize state (atomic write via temp file)
TMP=$(mktemp)
cat > "$TMP" << STATEEOF
{
  "task": ${TASK_JSON},
  "stage": "architect",
  "status": "running",
  "started_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "plan": null,
  "files": null,
  "review": null,
  "tests": null,
  "deploy": null
}
STATEEOF
mv "$TMP" "$STATE_FILE"

echo "🧠 Architect: State initialized. Plan will be generated by OpenClaw agent."
echo "🧠 Architect: Request saved to $STATE_FILE"
echo ""
echo "NEXT: OpenClaw should now read the request and generate a plan,"
echo "then run: bash clawforge.sh stage architect plan_complete"
