#!/usr/bin/env bash
# ClawForge — Stage 1: Architect
# Reads user request, produces a technical plan
set -euo pipefail

REQUEST="${1:-}"
STATE_FILE="${CLAWFORGE_STATE:-$HOME/.openclaw/workspace/clawforge-state.json}"
ARCHITECT_IDENTITY="$HOME/.openclaw/workspace/clawforge/agents/architect/IDENTITY.md"

if [ -z "$REQUEST" ]; then
  echo "Usage: plan.sh \"user request\""
  exit 1
fi

echo "🧠 Architect: Analyzing request..."

# Initialize state
cat > "$STATE_FILE" << STATEEOF
{
  "task": $(echo "$REQUEST" | jq -Rs .),
  "stage": "architect",
  "status": "running",
  "started_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "plan": null,
  "files": null,
  "review": null,
  "tests": null,
  "deploy": null
}
STATEEOF

echo "🧠 Architect: State initialized. Plan will be generated by OpenClaw agent."
echo "🧠 Architect: Request saved to $STATE_FILE"
echo ""
echo "NEXT: OpenClaw should now read the request and generate a plan,"
echo "then run: bash skills/clawforge/scripts/build.sh"
